version: "3.8"

services:
  

  backend:
    image: dineshkumar2026/mern-backend:latest
    container_name: backend
    restart: always
    env_file:
      - ./backend/.variables.env
    networks:
      - mernstack
    depends_on:
      - db

  frontend:
    image: dineshkumar2026/mern-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on: 
      - backend
    networks:
      - mernstack

  db:
    image: mongo:7
    container_name: mongo-db
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - mernstack

volumes:
  mongo-data:

networks:
  mernstack:
    driver: bridge